### ISSUE TITLE
DwCGeneric class overhaul

### ISSUE THREAD

**Issue by joechip90** [LivingNorway/LivingNorwayR#16]
There's a couple of problems that currently limits the usefulness of the DwcGeneric class to handle registered extensions for Darwin core. As it currently stands the metafile for the Darwin core archive requires IRIs for each defined term. These are autogenerated for the standard classes (using the functions in the DwCTerms.R source file) but for the DwCGeneric class we need to add a mechanism for the user to add these definitions otherwise DwCGeneric objects defined from registered extensions won't produce Darwin core archives that pass the validator.

I'm currently overhauling the interface for DwCGeneric that allows for the user to provide this information.

**Comment by joechip90** [comment]
Okay I'v emanaged to solve the problems with the DwCGeneric class by creating a new class 'DwCTerm' that contains all the required information to produce a valid Darwin core term. The package will automatically contain all the terms defined in the standard but this also allows the user to specifiy their own terms and add them to the archive.  This should make otu package extensible for newly added extensions to the standard

**Comment by joechip90** [comment]
Latest commit includes all the source code for the DwCTerm class. In addition it contains files to generate the list of registered terms (scraped from Darwin Core's website) and the classes with their associated terms

**Comment by ErlendNilsen** [comment]
@joechip90 Is the webscrape the same as this: https://github.com/tdwg/dwc/blob/master/vocabulary/term_versions.csv ?

**Comment by joechip90** [comment]
DwCGeneric class overhaul and all derived classes complete.  Uses webscrape from https://dwc.tdwg.org/terms/ and then adds in GBIF extensions using the information in https://rs.gbif.org/core/ and https://rs.gbif.org/extension/.  A lot more quality-of-life elements can be added but the basic functionality is there now
