### ISSUE TITLE
Error : 'C:/Users/matthew.grainger/Documents/Projects_in_development/Test_the_dataPackage/Rock_ptarmigan/metadata/metadata/metadata.Rmd' does not exist

### ISSUE THREAD

**Issue by andersfi** [LivingNorway/LivingNorwayR#24]
Testing out the LivingNorwayR but getting the error message below. Not time to debug myself rigth now, but hopefully a quick-fix?

```
Error : 'C:/Users/matthew.grainger/Documents/Projects_in_development/Test_the_dataPackage/Rock_ptarmigan/metadata/metadata/metadata.Rmd' does not exist.
Error: unable to load R code in package ‘LivingNorwayR’
Execution halted
```

Running on R version 3.6.3 (2020-02-29), x86_64, linux-gnu

**Comment by DrMattG** [comment]
I need to change the filepath using here::here() - sorry dumb mistake. I will let you know when it is fixed (there will be a big git-push when Joe gets back to Bergen so I will wait until after that if that is okay - let me know if you need it beforehand as I have some working code on another branch that I can give you for demonstration purposes). Matt

**Comment by ErlendNilsen** [comment]
@DrMattG @joechip90 It appears that this error/bug is still preventing us from building the package locally and/or install it using devtools::install_github()

**Comment by DrMattG** [comment]
I will see if I can work out why my fix did not work. I'll report back tomorrow

**Comment by DrMattG** [comment]
@ErlendNilsen can you try and install the package again please? Use devtools::install_github(......,force=TRUE). I think I found the error - it was a uncommented path used to test a function (the RStudio "find in" function is really useful).

**Comment by DrMattG** [comment]
It works!
