### ISSUE TITLE
Add parent ID in to tags

### ISSUE THREAD

**Issue by DrMattG** [LivingNorway/LivingNorwayR#44]
Allow tags to have a parent ID - Challenge to add parent ID to html code. Might need to build in a schema for LN. 
Need to append parent and child id (goes in to the html attribute) 

Needs unique IDs
users need to add ID and parent ID
e.g. creator1:creator_parentID:parent1

**Comment by joechip90** [comment]
I have created a new file 'LNtagHTML.R' that has an outline of how we can go about doing this.  It is still pretty barebones but you'll see three functions there.  One is 'LNaddTag' that is the base function that creates the HTML tags in the format the metadata scraper is expecting.  Format of the tag will be <span id="LN[tagID]_[parentID]" class="LNmetadata_[tagType]">.  If a parent ID is not given then the ID is only "LN[tagID]" and if the tag is to be hidden then style="display:none" is added to the tag.

I've create a function LNalternativeIdentifier which does exactly the same function as your version of the function, but just with the new setup.

Finally, there is a function getTagGenerationFunctions which is just a function that returns a named list of all the functions that we have included to produce EML information (just one entry so far).

**Comment by DrMattG** [comment]
@joechip90  I have made a pull request with updated addtag functions (Meta data #46). Is that safe to merge?

For the metadata that are nested tags I have listed all the component tags e.g. 
# individualName tag is firstName, lastName
I have not made a tag for individualName speficially - but have tags for firstName and for lastName so individualNAme can be made in the EML object - is that correct or do we need a set of composite tags (which would need a seperate,  I think, add_tag function)?
